overrides:
  '@easy-editor/core': link:../EasyEditor/packages/core
  '@easy-editor/react-renderer': link:../EasyEditor/packages/react-renderer
  '@easy-editor/react-renderer-dashboard': link:../EasyEditor/packages/react-renderer-dashboard
