packages:
  - .
  - server
  - viewer

allowBuilds:
  '@biomejs/biome': true
  esbuild: true

minimumReleaseAgeExclude:
  - '@supabase/auth-js@2.111.0'
  - '@supabase/functions-js@2.111.0'
  - '@supabase/postgrest-js@2.111.0'
  - '@supabase/realtime-js@2.111.0'
  - '@supabase/storage-js@2.111.0'
  - '@supabase/supabase-js@2.111.0'

patchedDependencies:
  '@easy-editor/core@1.0.3': patches/@easy-editor__core@1.0.3.patch
  '@easy-editor/react-renderer-dashboard@1.0.4': patches/@easy-editor__react-renderer-dashboard@1.0.4.patch
